// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Mvc.Data.Models
{
    public partial class Address
    {
        public Address()
        {
            Offices = new HashSet<Office>();
            Providers = new HashSet<Provider>();
        }

        public int Id { get; set; }
        public int IdSettlement { get; set; }
        public string Street { get; set; }
        public string IntNumber { get; set; }

        public virtual ZipCode IdSettlementNavigation { get; set; }
        public virtual ICollection<Office> Offices { get; set; }
        public virtual ICollection<Provider> Providers { get; set; }
    }
}