// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Mvc.Data.Models
{
    public partial class Product
    {
        public Product()
        {
            ProductOccasions = new HashSet<ProductOccasion>();
        }

        public int Id { get; set; }
        public int IdProvider { get; set; }
        public int IdCategory { get; set; }

        public virtual Category IdCategoryNavigation { get; set; }
        public virtual Provider IdProviderNavigation { get; set; }
        public virtual ICollection<ProductOccasion> ProductOccasions { get; set; }
    }
}