// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Mvc.Data.Models
{
    public partial class ProductOccasion
    {
        public int Id { get; set; }
        public int IdProduct { get; set; }
        public int IdOccasion { get; set; }

        public virtual Occasion IdOccasionNavigation { get; set; }
        public virtual Product IdProductNavigation { get; set; }
    }
}